# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

collections:
  crimes_en:
    language_code: en
    language_name: English
    output: true
    permalink: /en/:name
  crimes_hi:
    language_code: hi
    language_name: हिन्दी
    output: true
    permalink: /hi/:name
